@startuml
'https://plantuml.com/activity-diagram-beta

left header Remo Bergamin

partition Aufwärmübung {
    start

    :A;
    :B;
    :C;

    fork
        :D;
        :F;
    fork again
        :E;
    end fork {OR}

    :G;

    if () then ([x = 1])
        :H;
        stop
    else ([else])
        repeat
            :I;
            fork
                :J;
            fork again
                :K;
            fork end
            :L;
        repeat while () is ([y = 1])
        ->[y = 2];
        stop
    endif
}
@enduml
