@startuml
'https://plantuml.com/activity-diagram-beta

left header Remo Bergamin

partition Pizzatest {
    start

    repeat
        :Zufällig 5 Exemplare
        selben Typs nehmen;
        :Auf Gefrierschäden untersuchen;

        if () then ([keine Gefrierschäden])
            :Bei 230°C 20min erhitzen;
            :Auf Essfertigkeit prüfen;

            if () then ([zu wenig oder zu stark gebacken])
                if () then ([> 1])
                    :Mitteilung an
                    Geschäftsleitung;
                else ([<= 1])
                endif
                :Mitteilung an
                Produktionsabteilung;

            else ([fehlerfrei gebacken])
                if () then ([Beanstandungen Geschmack])
                    if () then ([> 1])
                        :Mitteilung an
                        Geschäftsleitung;
                    else ([<= 1])
                    endif
                    :Mitteilung an
                    Abteilung Beschaffung;

                else ([keine Beanstandungen Geschmack])
                  stop
                endif
            endif

        else ([Gefrierschäden])
            if () then ([> 1])
                :Mitteilung an
                Geschäftsleitung;
            else ([<= 1])
            endif
            :Mitteilung an
            Produktionsabteilung;
        endif
    repeat while
}

@enduml
